plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme@pcmultlect

kramdown:
   parse_block_html: true

include:
   - _pages
exclude:
   - vendor
   - setup.sh
   - jekyll.sh
   - .sass-cache
   - Gemfile
   - LICENSE
   - .bundle

timezone: America/Los_Angeles

url: https://ucsb-cs56.github.io # the base hostname & protocol for your site
baseurl: /w20  # the subpath of your site, e.g. "/blog"
github_url: https://github.com/ucsb-cs56/w20



course: "CS56"
qtr: "W20"
qxx: "w20"
quarter: "Winter 2020"

lecture_days_of_week: MTWR

assigned_text: " assigned(MW)"
assigned2_text: " assigned(TR)"
due_text: " due(MW) "
due2_text: " due(TR) "

start_week: 1
start_date: 2020-01-05
num_weeks: 10
extra_exam_week: true

cal_dates: >
  [
    {"label":"W20 1st day of instruction", "date":"2020-01-06" },	
    {"label":"Univ Holiday", "date":"2020-01-20" , "holiday": true},
    {"label":"Univ Holiday", "date":"2020-02-17", "holiday": true},
    {"label":"W20 instruction ends", "date":"2020-03-13" },
    {"label":"W20 finals start", "date":"2020-03-14" },
    {"label":"W20 finals end", "date":"2020-03-20" },
    {"label":"TR final noon-3pm", "date":"2020-03-18" },
    {"label":"MW final noon-3pm", "date":"2020-03-17" },		
    {"label":"W20 qtr ends", "date":"2020-03-20" }
  ]

piazza_url: https://piazza.com
gauchospace_course_page: https://gauchospace.ucsb.edu/courses/course/view.php?id=tbd
github_org_name: ucsb-cs56-w20
github_org_url: https://github.com/ucsb-cs56-w20

ta_list: "Scott and Zachary"
ta_list_full: "Scott Chow and Zachary Sisco"
mentors_list: "TBA"
discussion_section_times: "5pm,&nbsp;6pm,&nbsp;7pm"


mentor_url: https://ucsb-cs56-pconrad-mentors.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048
hfj_url: book/programming/java/0596009208
hfdp_url: book/software-engineering-and-development/patterns/0596007124 

legacy_wiki_url: https://foo.cs.ucsb.edu/56wiki
legacy_wiki_name: "56wiki"


sections: "5pm,&nbsp;6pm,&nbsp;7pm"


hwk_drop_lowest: three

legacy_wiki_name: 56wiki
legacy_wiki_url: "https://foo.cs.ucsb.edu/56wiki" 


hfj_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfj/HFJ_Chapter_"
hfdp_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfdp/HFDP_Chapter_"


collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  hwkWIP:
    output: true
    permalink: /hwkWIP/:path/
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  staff:
    output: true
    permalink: /staff/:path



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: hwkWIP
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: staff
    values:
     layout: staff

  - scope:
     path: ""
     type: pages
    values:
     layout: default

head_scripts:
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
   - /static/js/select_section.js

